In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
Y_hat = np.linspace(-3, 3, 100)
Y = np.random.randint(2, size=(100))

[0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1
 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 0 0 1 1 1 0 1 1]


In [5]:
print (Y_hat.shape)
print (Y.shape)

print (Y_hat)
print (Y)

(100,)
(100,)
[-3.         -2.93939394 -2.87878788 -2.81818182 -2.75757576 -2.6969697
 -2.63636364 -2.57575758 -2.51515152 -2.45454545 -2.39393939 -2.33333333
 -2.27272727 -2.21212121 -2.15151515 -2.09090909 -2.03030303 -1.96969697
 -1.90909091 -1.84848485 -1.78787879 -1.72727273 -1.66666667 -1.60606061
 -1.54545455 -1.48484848 -1.42424242 -1.36363636 -1.3030303  -1.24242424
 -1.18181818 -1.12121212 -1.06060606 -1.         -0.93939394 -0.87878788
 -0.81818182 -0.75757576 -0.6969697  -0.63636364 -0.57575758 -0.51515152
 -0.45454545 -0.39393939 -0.33333333 -0.27272727 -0.21212121 -0.15151515
 -0.09090909 -0.03030303  0.03030303  0.09090909  0.15151515  0.21212121
  0.27272727  0.33333333  0.39393939  0.45454545  0.51515152  0.57575758
  0.63636364  0.6969697   0.75757576  0.81818182  0.87878788  0.93939394
  1.          1.06060606  1.12121212  1.18181818  1.24242424  1.3030303
  1.36363636  1.42424242  1.48484848  1.54545455  1.60606061  1.66666667
  1.72727273  1.78787879  1.84848485  1

In [13]:
TY_hat = torch.Tensor(Y_hat.reshape(-1, 1))
TY = torch.Tensor(Y.reshape(-1, 1))

In [15]:
print (TY_hat.size())
print (TY.size())

torch.Size([100, 1])
torch.Size([100, 1])


In [14]:
loss = F.nll_loss(TY, TY_hat).numpy()
plt.plot(Y_hat, loss)
plt.show()

RuntimeError: 1D target tensor expected, multi-target not supported

In [37]:
batch_size = 7
ref=np.array([[0,1,0],[0,0,1],[1,0,0]])
actions=np.array([[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]])
ip = np.random.randint(len(actions), size=(batch_size))
print (ip)
ip = torch.Tensor(ref[actions[ip]].reshape(-1, 6))
print (ip.size())
print (ip)

op = np.random.randint(len(actions), size=(batch_size))
print (op)
op = torch.Tensor(ref[actions[op]].reshape(-1, 6))
print (op.size())
print (op)

[4 5 1 6 1 2 4]
torch.Size([7, 6])
tensor([[0., 1., 0., 0., 0., 1.],
        [0., 0., 1., 1., 0., 0.],
        [1., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 1.]])
[0 7 6 1 5 3 7]
torch.Size([7, 6])
tensor([[1., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 1.],
        [0., 0., 1., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0.],
        [0., 0., 1., 1., 0., 0.],
        [0., 1., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 1.]])


In [21]:
loss = F.nll_loss(ip, op)
print (loss)

RuntimeError: 1D target tensor expected, multi-target not supported

In [26]:
loss = F.binary_cross_entropy(ip, op, reduction='none')
print (loss)

loss = F.binary_cross_entropy(ip, ip, reduction='none')
print (loss)

tensor([[-0.0000, -0.0000, -0.0000, 27.6310, -0.0000, 27.6310],
        [27.6310, 27.6310, -0.0000, -0.0000, 27.6310, 27.6310],
        [27.6310, -0.0000, 27.6310, 27.6310, 27.6310, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
        [27.6310, -0.0000, 27.6310, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, 27.6310, 27.6310, -0.0000]])
tensor([[-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.]])


In [35]:
batch_size = 7
ref=torch.FloatTensor([[0,1,0],[0,0,1],[1,0,0]])
actions=np.array([[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]])
ip = np.random.randint(len(actions), size=(batch_size))
print (ip)
ip = torch.Tensor(ref[actions[ip][0]].reshape(-1, 3))
print (ip.size())
print (ip)

[2 3 1 7 7 0 3]
torch.Size([2, 3])
tensor([[1., 0., 0.],
        [0., 0., 1.]])


In [2]:
u = np.random.randint(3, size=(7,3)).astype(float)
print (u)

[[1. 0. 2.]
 [0. 1. 1.]
 [1. 2. 0.]
 [2. 0. 2.]
 [2. 2. 2.]
 [0. 1. 2.]
 [0. 2. 2.]]


In [28]:
F.one_hot(torch.as_tensor(u), num_classes=3)

RuntimeError: one_hot is only applicable to index tensor.

In [3]:
u = torch.randint(3, (7, 2))
u

tensor([[0, 1],
        [0, 0],
        [0, 1],
        [1, 0],
        [2, 1],
        [0, 2],
        [2, 2]])

In [4]:
u_pred = torch.rand((7, 6))
u_pred

tensor([[0.6912, 0.7963, 0.2135, 0.0889, 0.6857, 0.7890],
        [0.6778, 0.0267, 0.8479, 0.4313, 0.7546, 0.6323],
        [0.2613, 0.5831, 0.9990, 0.0540, 0.6356, 0.9053],
        [0.7254, 0.3476, 0.6796, 0.5114, 0.7360, 0.4318],
        [0.7253, 0.6331, 0.8383, 0.8307, 0.7396, 0.8269],
        [0.2946, 0.2983, 0.9700, 0.2741, 0.3861, 0.6752],
        [0.5681, 0.4283, 0.5445, 0.1252, 0.7448, 0.1290]])

In [5]:
lx = F.cross_entropy(u_pred[:, :3], u[:, 0], reduction='none')
ly = F.cross_entropy(u_pred[:, 3:], u[:, 1], reduction='none')
print (lx)
print (ly)

tensor([1.0047, 0.9958, 1.4975, 1.3488, 0.9961, 1.3784, 1.0696])
tensor([0.9781, 1.2821, 1.0538, 1.1554, 1.1589, 0.8832, 1.3474])


In [27]:
ip = u_pred[:, 3:]
argMax = torch.argmax(ip, dim=1, keepdims=True)
print (argMax)
op = torch.zeros_like(ip)
src=torch.tensor(torch.ones_like(argMax), dtype=torch.float)
print (src)
op.scatter_(1, argMax, value=1.0)
print (op)

tensor([[2],
        [1],
        [2],
        [1],
        [0],
        [2],
        [1]])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
tensor([[0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]])


/Users/pradeepkadubandi/.local/share/virtualenvs/DemoPlanner--5SJrBy7/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """


In [17]:
u_pred = F.one_hot(torch.tensor(u, dtype=torch.long))
u_pred = torch.reshape(u_pred, (u_pred.size()[0], -1))
u_pred = torch.tensor(u_pred, dtype=torch.float)
u_pred = u_pred - math.pow(10, -30)
u_pred

/Users/pradeepkadubandi/.local/share/virtualenvs/DemoPlanner--5SJrBy7/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
/Users/pradeepkadubandi/.local/share/virtualenvs/DemoPlanner--5SJrBy7/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([[-1.0000e-30,  1.0000e+00, -1.0000e-30,  1.0000e+00, -1.0000e-30,
         -1.0000e-30],
        [-1.0000e-30, -1.0000e-30,  1.0000e+00, -1.0000e-30,  1.0000e+00,
         -1.0000e-30],
        [-1.0000e-30, -1.0000e-30,  1.0000e+00, -1.0000e-30, -1.0000e-30,
          1.0000e+00],
        [-1.0000e-30, -1.0000e-30,  1.0000e+00, -1.0000e-30,  1.0000e+00,
         -1.0000e-30],
        [-1.0000e-30, -1.0000e-30,  1.0000e+00,  1.0000e+00, -1.0000e-30,
         -1.0000e-30],
        [-1.0000e-30, -1.0000e-30,  1.0000e+00, -1.0000e-30, -1.0000e-30,
          1.0000e+00],
        [-1.0000e-30,  1.0000e+00, -1.0000e-30,  1.0000e+00, -1.0000e-30,
         -1.0000e-30]])

In [18]:
lx = F.cross_entropy(u_pred[:, :3], u[:, 0], reduction='none')
ly = F.cross_entropy(u_pred[:, 3:], u[:, 1], reduction='none')
print (lx)
print (ly)

tensor([0.5514, 0.5514, 0.5514, 0.5514, 0.5514, 0.5514, 0.5514])
tensor([0.5514, 0.5514, 0.5514, 0.5514, 0.5514, 0.5514, 0.5514])


In [27]:
F.cross_entropy(torch.Tensor([[0,0,1]]), torch.LongTensor([2]))

tensor(0.5514)

In [48]:
u_pred = torch.rand((7, 2))
u_pred

tensor([[0.7448, 0.5683],
        [0.4792, 0.4464],
        [0.1592, 0.3000],
        [0.6917, 0.6731],
        [0.9426, 0.9293],
        [0.1921, 0.4872],
        [0.6835, 0.6908]])

In [52]:
F.binary_cross_entropy(u_pred, torch.tensor(u, dtype=torch.float))

/Users/pradeepkadubandi/.local/share/virtualenvs/DemoPlanner--5SJrBy7/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor(0.8587)

In [9]:
x = torch.rand((3,2))
y = torch.rand((3,2))
print (x)
print (y)

tensor([[0.0758, 0.1743],
        [0.7820, 0.0297],
        [0.0083, 0.0317]])
tensor([[0.7893, 0.6317],
        [0.2436, 0.9800],
        [0.9898, 0.8833]])


In [10]:
print(F.l1_loss(x,y))
print(torch.sum(torch.abs(x-y)) / len(x[0]))

tensor(0.7488)
tensor(2.2464)


In [44]:
labels = torch.Tensor(ref[u.numpy()].reshape(u.size()[0], -1))
labels = torch.tensor(labels, dtype=torch.long).detach()
labels

/Users/pradeepkadubandi/.local/share/virtualenvs/DemoPlanner--5SJrBy7/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


tensor([[0, 0, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 1, 0],
        [0, 1, 0, 1, 0, 0]])

In [27]:
print (F.log_softmax(torch.Tensor([-300,-300,300]), dim=0))

tensor([-600., -600.,    0.])


In [ ]:
n = MultiNet(policy, dynamics)
labels = torch.tensor(torch.randint(2, size=(7, 2)), dtype=torch.float)
ip = torch.rand((7, 4))
op = n(ip)

In [ ]:
# print (n.lsmax_x)
# print (n.x.size())
# print (n.dynamics_input)
print (ip)
print (op)
print (labels)

In [ ]:
pol_op = n.policy(ip)
print (pol_op)

In [ ]:
lsmax_x = F.log_softmax(pol_op[:, :3], dim=1)
lsmax_y = F.log_softmax(pol_op[:, 3:], dim=1)
print (lsmax_x)
print (lsmax_y)

In [ ]:
ux = ArgMaxFunction.apply(pol_op[:, :3])
uy = ArgMaxFunction.apply(pol_op[:, 3:])
print (ux)
print (uy)

In [ ]:
opt = torch.optim.Adam(n.parameters())
opt.zero_grad()
loss = F.mse_loss(op, labels)
print (loss)
loss.backward()

In [ ]:
for p in n.dynamics.net[0].parameters():
    print (p.grad)

In [ ]:
for p in n.policy.net[4].parameters():
    print (p.grad)

In [2]:
op = torch.rand(7, 4)
target = torch.rand(7, 4)
print (op)
print (target)

tensor([[0.3520, 0.0755, 0.2014, 0.6903],
        [0.1428, 0.6354, 0.7112, 0.4009],
        [0.2296, 0.1016, 0.5332, 0.6085],
        [0.6748, 0.3949, 0.1802, 0.4519],
        [0.8270, 0.0598, 0.1178, 0.8238],
        [0.1448, 0.3695, 0.2893, 0.1801],
        [0.1378, 0.9065, 0.5708, 0.4378]])
tensor([[0.2261, 0.4202, 0.2911, 0.5113],
        [0.9506, 0.4345, 0.0396, 0.6541],
        [0.4150, 0.8787, 0.3546, 0.7274],
        [0.6981, 0.1774, 0.3505, 0.5261],
        [0.0616, 0.0096, 0.2349, 0.9663],
        [0.2116, 0.3250, 0.2333, 0.5471],
        [0.0988, 0.6595, 0.5047, 0.2442]])


In [11]:
print (F.l1_loss(op, target))
loss_unreduced = F.l1_loss(op, target, reduction='none')

tensor(0.2348)


In [14]:
loss_per_sample = torch.sum(loss_unreduced, dim=1) / loss_unreduced.size()[1]
print (loss_per_sample)
best = torch.argmin(loss_per_sample)
worst = torch.argmax(loss_per_sample)
print (best)
print (worst)

tensor([0.1848, 0.4834, 0.3150, 0.1213, 0.2688, 0.1336, 0.1364])
tensor(3)
tensor(1)


In [2]:
II = F.l1_loss(torch.rand(7, 13),torch.rand(7, 13), reduction='none')
IY = F.l1_loss(torch.rand(7, 4),torch.rand(7, 4), reduction='none')

In [3]:
print (II.size())
print (IY.size())

torch.Size([7, 13])
torch.Size([7, 4])


In [4]:
l = torch.cat((II,IY), dim=1)
l.size()

torch.Size([7, 17])

In [5]:
torch.sum(l, dim=1) / l.size()[1]

tensor([0.3268, 0.3816, 0.4310, 0.3497, 0.2632, 0.4270, 0.2615])

In [6]:
torch.rand(1024).view((-1,1,32,32)).size()

torch.Size([1, 1, 32, 32])

In [6]:
print (torch.round(torch.Tensor([.99, .5, .2, -0.2, -0.5, -0.99])))
print (torch.round(torch.Tensor([1.5, -1.5, 1.7, -1.7, 1.4, 1.6, 0.5, 0.55])))

tensor([ 1.,  0.,  0., -0., -0., -1.])
tensor([ 2., -2.,  2., -2.,  1.,  2.,  0.,  1.])


In [5]:
t = torch.Tensor([31,32,28,32,29,0,1])
torch.where(t == 32, t-1, t)

tensor([31., 31., 28., 31., 29.,  0.,  1.])